# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e7c85ba4d7c2940f8766de6b694a577c20255528d238db7f842a8d3c66551556c145de72ef0d7d7ea7a5453a71e88cdc3640c7c4ae1adb71b0c1c79d8211736

test:
  secret_key_base: 2a9457a3fcae55c6f233a2cabd8f37245576971a7c89f650f40ad822149629010aa86960861d4521998f0803e5080ba9a6deafbe972740a7f39e016e683628b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
